network/urls.py
from django.urls import path

from . import views

app_name = "network"
urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.home, name="home"),
    # path("<str:username>", views.profile, name="profile"),
    # path("explore", views.explore, name="explore"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
"""Django Docs

    https://docs.djangoproject.com/en/5.1/topics/db/                        --> All topics for models and databases

    https://docs.djangoproject.com/en/5.1/topics/db/models/                 --> Models (NOTE: Start here)

    https://docs.djangoproject.com/en/5.1/ref/models/fields/#field-types    --> field types

    https://docs.djangoproject.com/en/5.1/ref/models/fields/#field-options  --> field options

    https://docs.djangoproject.com/en/5.1/ref/models/options/               --> Models' internal class Meta and the options you can pass to it (like 'ordering')

    https://docs.djangoproject.com/en/5.1/topics/db/queries/#related-objects    --> related objects (ie. foreign key, ManyToMany field)

    https://docs.djangoproject.com/en/5.1/topics/db/examples/                   --> examples of how to use related objects

    https://docs.djangoproject.com/en/5.1/ref/models/relations/                 --> related object reference page


    https://docs.djangoproject.com/en/5.1/topics/db/queries/                    --> making queries (NOTE: more useful for views.py)

    https://docs.djangoproject.com/en/5.1/ref/models/querysets/#field-lookups   --> field lookups (NOTE: more useful for views.py)

    https://docs.djangoproject.com/en/5.1/ref/models/querysets/                 --> QuerySet ref page


"""

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):
    """Model representing a User"""

    date_joined = models.DateField(auto_now=True, help_text="Date joined")

    # users subscribed to this user
    followers = models.ManyToManyField(
        "User",
        blank=True,
        help_text="Following user",
        related_name="following_user",
    )

    # track with logic
    num_followers = models.IntegerField(default=0)

    # users this user is subscribed to
    following = models.ManyToManyField(
        "User",
        blank=True,
        help_text="Followed by user",
        related_name="followed_by_user",
    )

    # track with logic
    num_following = models.IntegerField(default=0)

    # liked replies of this user
    likes = models.ManyToManyField(
        "Reply",
        blank=True,
        help_text="Liked posts",
        related_name="users_who_liked",
    )

    def __str__(self):
        return self.username

    def get_followers(self):
        return self.followers.all()

    def get_following(self):
        return self.following.all()


# NOTE:
# - pending:
#   - decide how to handle deleted replies
#
class Reply(models.Model):
    """Model representing a Post/Reply"""

    # NOTE:
    # - Facts about Reply:
    #
    #   - a reply is never deleted from the database (to simulate deletion track its 'deleted' field)
    #   - a reply with no 'replying_to' field is also an original post 'reply_type'

    # NOTE:
    # - a Reply will remain even when the 'replier' is deleted
    # (in this case the 'deleted' Reply field should be updated to True and the 'reply_message' erased)
    #
    replier = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,  # sets 'replier' to null if the user is deleted
        null=True,
        blank=True,
        related_name="replies",
    )

    # NOTE:
    # - a Reply will remain even when the parent reply (the post that is being replied to) is deleted
    # (its parent reply is never actually deleted, its 'deleted' field is tracked for this purpose - see 'Facts about Reply' above)
    replying_to = models.ForeignKey(
        "Reply",
        on_delete=models.PROTECT,  # makes sure referenced object is not deleted by raising exception
        related_name="replies",
        null=True,
        blank=True,
    )

    types_of_replies = [
        ("OP", "original post"),
        ("Reply", "reply"),
    ]

    reply_type = models.CharField(
        max_length=5, choices=types_of_replies, default="OP", help_text="Type of reply"
    )

    # track with logic
    num_likes = models.IntegerField(default=0)

    reply_message = models.CharField(max_length=280, help_text="What is happening!?")

    # track with logic
    num_direct_replies = models.IntegerField(default=0)

    reply_date = models.DateTimeField(default=timezone.now)

    # track with logic
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"Reply '{self.id}' from user {self.replier.username}"

    class Meta:
        ordering = ["-reply_date"]

network/forms.py
"""Django Docs

    https://docs.djangoproject.com/en/5.1/topics/forms/             --> working with forms

    https://docs.djangoproject.com/en/5.1/ref/forms/fields/         --> form fields

    https://docs.djangoproject.com/en/5.1/ref/forms/fields/#error-messages      --> error messages

    https://docs.djangoproject.com/en/5.1/topics/class-based-views/generic-editing/     --> form handling with class-based views

    
"""

network/views.py
"""Django Docs

    https://docs.djangoproject.com/en/5.1/topics/http/views/        --> primer on writing views

    https://docs.djangoproject.com/en/5.1/topics/http/shortcuts/    --> shortcut functions commonly used in views.py

    https://docs.djangoproject.com/en/5.1/topics/class-based-views/intro/       --> class-based views

    https://docs.djangoproject.com/en/5.1/topics/class-based-views/generic-display/     --> built-in views

"""

from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User, Reply


def index(request):
    return HttpResponseRedirect(reverse("network:home"))


def home(request):
    # NOTE:
    # - pending: paginate | limit entries (e.g. 20 + infinite scrolling)

    all_posts = Reply.objects.all()

    context = {"posts": all_posts}
    return render(request, "network/render_template/home.html", context)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(
                request,
                "network/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(
                request, "network/register.html", {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request, "network/register.html", {"message": "Username already taken."}
            )
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")

network/templates/network/components/component_navigation.html
{% comment 'Context' %} 

    user ('User' Model)
    

{% endcomment %}
{% load static %}
<div class="navigation">
    <div class="nav-chunk">
        <div class="nav-chunk-item">
            <a href="">
                <div class="site-logo">TwitteX</div>
            </a>
        </div>
        <div class="nav-chunk-item">
            <a href="">
                <div>
                    <img src="{% static "network/images/home_icon.svg" %}" alt="home icon" width="26" height="26">
                    <span>Home</span>
                </div>
            </a>
            <a href="">
                <div>
                    <img src="{% static "network/images/profile_icon_active.svg" %}" alt="profile icon" width="26" height="26">
                    <span>Profile</span>
                </div>
            </a>
        </div>
        <div class="nav-chunk-item">
            <a>
                <div class="post-button">Post</div>
            </a>
        </div>
    </div>
    <div class="nav-chunk">
        <div class="nav-chunk-item">
            {% if user.is_authenticated %}
                <a href="{% url 'network:logout' %}">
                    <div>
                        <img src="{% static "network/images/logout_icon.svg" %}" alt="logout icon" width="26" height="26">
                        <span>Logout</span>
                    </div>
                </a>
            {% else %}
                <a href="{% url 'network:login' %}">
                    <div>
                        <img src="{% static "network/images/login_icon.svg" %}" alt="login icon" width="26" height="26">
                        <span>Login</span>
                    </div>
                </a>
                <a href="{% url 'network:register' %}">
                    <div>
                        <img src="{% static "network/images/signup_icon.svg" %}" alt="profile icon" width="26" height="26">
                        <span>Sign Up</span>
                    </div>
                </a>
            {% endif %}
        </div>
    </div>
</div>

network/templates/network/components/modal.html
{% comment 'Context' %} 

    var: user, model: User
    var: post, model: Reply

{% endcomment %}
{% comment 'Blocks' %} 
              
    modal_content          
    
{% endcomment %}
{% comment 'Classes used in JS' %} 
              
    .modal-overlay
    .modal-set-height
    .close-button          
    
{% endcomment %}
{% load static %}
<div class="modal-overlay hide">
    <div class="modal-set-height">
        <div class="modal-wrapper flex flex-column">
            <div>
                <button aria-label="Close" role="button" class="close-button" type="button">
                    <div class="svg-close-wrapper flex flex-center" title="Close">
                        <div class="svg-wrapper flex flex-center border-pill background-transition">
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 viewBox="0 0 24 24"
                                 aria-hidden="true"
                                 class="">
                                <g>
                                <path d="M10.59 12L4.54 5.96l1.42-1.42L12 10.59l6.04-6.05 1.42 1.42L13.41 12l6.05 6.04-1.42 1.42L12 13.41l-6.04 6.05-1.42-1.42L10.59 12z">
                                </path>
                                </g>
                            </svg>
                        </div>
                    </div>
                </button>
            </div>
            {% block modal_content %}
            {% endblock modal_content %}
        </div>
    </div>
</div>

network/templates/network/components/modal_write_post.html
{% extends "network/components/modal.html" %}
{% comment 'Context' %} 

    var: user, model: User
    var: post, model: Reply

{% endcomment %}
{% comment 'Blocks' %} 
              
    modal_content           - inherited, from modal.html
    
{% endcomment %}
{% load static %}
{% block modal_content %}
    <div class="utility-wrapper">
        <div class="utility-wrapper">
            <div class="flex">
                {% block profile_icon %}
                    {% include "network/components/post_profile_icon_not_interactive.html" %}
                {% endblock profile_icon %}
                <div class="write-message-wrapper flex-1">
                    <div>
                        <span class="message-content" contenteditable="true"></span>
                        <span class="message-placeholder">What is happening?!</span>
                    </div>
                </div>
            </div>
            <div class="form-spacing"></div>
            <div class="form-post-button-wrapper flex flex-main-end flex-cross-end">
                <button type="button"
                        disabled="true"
                        class="form-post-button disabled border-pill flex flex-center background-transition">
                    <div>Post</div>
                </button>
            </div>
        </div>
    </div>
{% endblock modal_content %}

network/templates/network/components/navigation.html
{% comment 'Context' %} 

    var: user, model: User
    
{% endcomment %}
{% load static %}
<div class="navigation">
    <div class="nav-chunk">
        <div class="nav-chunk-item">
            <a href="">
                <div class="site-logo">TwitteX</div>
            </a>
        </div>
        <div class="nav-chunk-item">
            <a href="">
                <div>
                    <img src="{% static "network/images/home_icon.svg" %}" alt="home icon" width="26" height="26">
                    <span>Home</span>
                </div>
            </a>
            <a href="">
                <div>
                    <img src="{% static "network/images/profile_icon_active.svg" %}" alt="profile icon" width="26" height="26">
                    <span>Profile</span>
                </div>
            </a>
        </div>
        <div class="nav-chunk-item">
            <a>
                <div class="post-button">Post</div>
            </a>
        </div>
    </div>
    <div class="nav-chunk">
        <div class="nav-chunk-item">
            {% if user.is_authenticated %}
                <a href="{% url 'network:logout' %}">
                    <div>
                        <img src="{% static "network/images/logout_icon.svg" %}" alt="logout icon" width="26" height="26">
                        <span>Logout</span>
                    </div>
                </a>
            {% else %}
                <a href="{% url 'network:login' %}">
                    <div>
                        <img src="{% static "network/images/login_icon.svg" %}" alt="login icon" width="26" height="26">
                        <span>Login</span>
                    </div>
                </a>
                <a href="{% url 'network:register' %}">
                    <div>
                        <img src="{% static "network/images/signup_icon.svg" %}" alt="profile icon" width="26" height="26">
                        <span>Sign Up</span>
                    </div>
                </a>
            {% endif %}
        </div>
    </div>
</div>

network/templates/network/components/post.html
{% comment 'Context' %} 

    var: user, model: User
    var: post, model: Reply

{% endcomment %}
{% comment 'Blocks' %} 

    - the blocks in this component are used primarily to exclude structure in 
    'reply_simplified.html' which is a simplified version of this component

        three_dots_icon             
        reply_bar                   
        reply_to                    
                     
    - it is also used to add the continuity line on 'reply.html'

        continuity_line


{% endcomment %}
{% load static %}
<div class="post">
    <div></div>
    <div class="post-content-wrapper">
        {% block post_profile_icon %}
            {% include "network/components/post_profile_icon.html" %}
        {% endblock post_profile_icon %}
        <div class="utility-wrapper flex-1">
            <div class="post-content">
                <div class="post-meta flex justify-content-space-between">
                    <div class="name-handle-date-wrapper">
                        <a href="">{{ post.replier.first_name }}</a>
                        <a href="">@{{ post.replier.username }}</a>
                        <span>·</span>
                        <a href=""><time datetime="{{ post.reply_date|date:"c" }}">{{ post.reply_date|date:"M j, Y" }}</time></a>
                    </div>
                    {% block three_dots_icon %}
                        <div class="svg-more-wrapper svg-reply-wrapper flex flex-center"
                             title="More">
                            <div class="svg-wrapper flex flex-center border-pill background-transition">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 24 24"
                                     aria-hidden="true"
                                     class="">
                                    <g>
                                    <path d="M3 12c0-1.1.9-2 2-2s2 .9 2 2-.9 2-2 2-2-.9-2-2zm9 2c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm7 0c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2z">
                                    </path>
                                    </g>
                                </svg>
                            </div>
                        </div>
                    {% endblock three_dots_icon %}
                </div>
                <div class="message-wrapper">
                    <span>{{ post.reply_message }}</span>
                </div>
                {% block reply_bar %}
                    <div class="reply-repost-like-wrapper">
                        <div class="svg-reply-wrapper flex flex-center" title="Reply">
                            <div class="svg-wrapper flex flex-center border-pill background-transition">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 24 24"
                                     aria-hidden="true"
                                     class="">
                                    <g>
                                    <path d="M1.751 10c0-4.42 3.584-8 8.005-8h4.366c4.49 0 8.129 3.64 8.129 8.13 0 2.96-1.607 5.68-4.196 7.11l-8.054 4.46v-3.69h-.067c-4.49.1-8.183-3.51-8.183-8.01zm8.005-6c-3.317 0-6.005 2.69-6.005 6 0 3.37 2.77 6.08 6.138 6.01l.351-.01h1.761v2.3l5.087-2.81c1.951-1.08 3.163-3.13 3.163-5.36 0-3.39-2.744-6.13-6.129-6.13H9.756z">
                                    </path>
                                    </g>
                                </svg>
                            </div>
                            <div class="count text-small color-transition">300</div>
                        </div>
                        <div class="svg-repost-wrapper flex flex-center" title="Repost">
                            <div class="svg-wrapper flex flex-center border-pill background-transition">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 24 24"
                                     aria-hidden="true"
                                     class="">
                                    <g>
                                    <path d="M4.5 3.88l4.432 4.14-1.364 1.46L5.5 7.55V16c0 1.1.896 2 2 2H13v2H7.5c-2.209 0-4-1.79-4-4V7.55L1.432 9.48.068 8.02 4.5 3.88zM16.5 6H11V4h5.5c2.209 0 4 1.79 4 4v8.45l2.068-1.93 1.364 1.46-4.432 4.14-4.432-4.14 1.364-1.46 2.068 1.93V8c0-1.1-.896-2-2-2z">
                                    </path>
                                    </g>
                                </svg>
                            </div>
                            <div class="count text-small color-transition">300</div>
                        </div>
                        <div class="svg-like-wrapper flex flex-center" title="Like">
                            <div class="svg-wrapper flex flex-center border-pill background-transition">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 24 24"
                                     aria-hidden="true"
                                     class="">
                                    <g>
                                    <path d="M16.697 5.5c-1.222-.06-2.679.51-3.89 2.16l-.805 1.09-.806-1.09C9.984 6.01 8.526 5.44 7.304 5.5c-1.243.07-2.349.78-2.91 1.91-.552 1.12-.633 2.78.479 4.82 1.074 1.97 3.257 4.27 7.129 6.61 3.87-2.34 6.052-4.64 7.126-6.61 1.111-2.04 1.03-3.7.477-4.82-.561-1.13-1.666-1.84-2.908-1.91zm4.187 7.69c-1.351 2.48-4.001 5.12-8.379 7.67l-.503.3-.504-.3c-4.379-2.55-7.029-5.19-8.382-7.67-1.36-2.5-1.41-4.86-.514-6.67.887-1.79 2.647-2.91 4.601-3.01 1.651-.09 3.368.56 4.798 2.01 1.429-1.45 3.146-2.1 4.796-2.01 1.954.1 3.714 1.22 4.601 3.01.896 1.81.846 4.17-.514 6.67z">
                                    </path>
                                    </g>
                                </svg>
                            </div>
                            <div class="count text-small color-transition">300</div>
                        </div>
                        <div></div>
                    </div>
                {% endblock reply_bar %}
            </div>
            {% block reply_to %}
            {% endblock reply_to %}
        </div>
    </div>
</div>

network/templates/network/components/post_profile_icon.html
{% comment 'Context' %} 

    var: user, model: User
    var: post, model: Reply

{% endcomment %}
{% comment 'Blocks' %} 

    continuity_line

{% endcomment %}
<div class="post-profile-wrapper">
    <div class="post-profile-icon">
        <a href="">
            <div></div>
        </a>
        <div class="post-profile-overlay"></div>
    </div>
    {% block continuity_line %}
    {% endblock continuity_line %}
</div>

network/templates/network/components/post_profile_icon_not_interactive.html
{% comment 'Context' %} 

    var: user, model: User
    var: post, model: Reply

{% endcomment %}
{% comment 'Blocks' %} 

    continuity_line

{% endcomment %}
{% comment 'Notes' %}  

    - for now just a copy-paste file from 'post_profile_icon.html' with couple commented out sections
    - might extend 'post_profile_icon.html' later on instead

{% endcomment %}
<div class="post-profile-wrapper">
    <div class="post-profile-icon">
        <a {% comment %}href=""{% endcomment %}>
            <div></div>
        </a>
        {% comment %}<div class="post-profile-overlay"></div>{% endcomment %}
    </div>
    {% block continuity_line %}
    {% endblock continuity_line %}
</div>

network/templates/network/components/post_profile_icon_reply.html
{% extends "network/components/post_profile_icon.html" %}
{% comment %} adds continuity line {% endcomment %}
{% block continuity_line %}
    <div class="continuity-line"></div>
{% endblock continuity_line %}

network/templates/network/components/reply.html
{% comment 'Context' %} 

    var: user, model: User
    var: post, model: Reply

{% endcomment %}
{% comment 'Blocks' %} 

    - the blocks in this component are used primarily to exclude structure in 
    'reply_simplified.html' which is a simplified version of this component

    - it is also used to add the continuity line on 'reply.html'

    section_main            - inherited, post.html

{% endcomment %}
{% load static %}
<div class="post">
    <div></div>
    <div class="post-content-wrapper">
        <div class="post-profile-icon">
            <a href="">
                <div></div>
            </a>
            <div class="post-profile-overlay"></div>
        </div>
        <div class="post-content">
            <div class="post-meta flex justify-content-space-between">
                <div class="name-handle-date-wrapper">
                    <a href="">{{ post.replier.first_name }}</a>
                    <a href="">@{{ post.replier.username }}</a>
                    <span>·</span>
                    <a href=""><time datetime="{{ post.reply_date|date:"c" }}">{{ post.reply_date|date:"M j, Y" }}</time></a>
                </div>
            </div>
            <div class="message-wrapper">
                <span>{{ post.reply_message }}</span>
            </div>
            <div></div>
        </div>
    </div>
</div>

network/templates/network/components/reply_simplified.html
{% extends "network/components/post.html" %}
{% comment 'Context' %} 

    var: user, model: User
    var: post, model: Reply

{% endcomment %}
{% comment 'Blocks' %} 

    three_dots_icon             - inherited, post.html
    reply_bar                   - inherited, post.html
    reply_to                    - inherited, post.html
    post_profile_icon           - inherited, post.html

{% endcomment %}
{% comment %} adds continuity line {% endcomment %}
{% block post_profile_icon %}
    {% include "network/components/post_profile_icon_reply.html" %}
{% endblock post_profile_icon %}
{% comment %} empties 'three_dots_icon' {% endcomment %}
{% block three_dots_icon %}
{% endblock three_dots_icon %}
{% comment %} empties 'reply_bar' {% endcomment %}
{% block reply_bar %}
{% endblock reply_bar %}
{% block reply_to %}
    <div class="reply-to">
        Replying to <span class="reply-to-username">@{{ post.replier.username }}</span>
    </div>
{% endblock reply_to %}

network/templates/network/index.html
{% extends "network/layout.html" %}
{% block body %}
    {% comment %} Reply
reply.replier.username
reply.reply_date
reply.reply_message

    {% endcomment %}
    {% for reply in replies %}
        <div class="reply">
            <span>{{ reply.replier.username }}</span>·<span>{{ reply.reply_date }}</span>
            <div>{{ reply.reply_message }}</div>
        </div>
    {% endfor %}
{% endblock body %}

network/templates/network/layout.html
{% comment "--------- Django Docs ---------" %}

    https://docs.djangoproject.com/en/5.1/topics/templates/             -- primer on templates

    https://docs.djangoproject.com/en/5.1/ref/templates/language/       -- another primer from the ref section
    
    https://docs.djangoproject.com/en/5.1/ref/templates/builtins/       -- built-in template tags and filters

    https://docs.djangoproject.com/en/5.1/howto/overriding-templates/#extending-an-overridden-template      -- overriding templates

{% endcomment %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="description" content="foo">
        <meta name="keywords" content="bar,baz">
        <title>
            {% block title %}
                Social Network
            {% endblock title %}
        </title>
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
              crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Network</a>
            <div>
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#"><strong>{{ user.username }} (Profile)</strong></a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">Following</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="body">
            {% block body %}
            {% endblock body %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}
{% block body %}
    <h2>Login</h2>
    {% if message %}<div>{{ message }}</div>{% endif %}
    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus
                   class="form-control"
                   type="text"
                   name="username"
                   placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control"
                   type="password"
                   name="password"
                   placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>
    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>
{% endblock body %}

network/templates/network/register.html
{% extends "network/layout.html" %}
{% block body %}
    <h2>Register</h2>
    {% if message %}<div>{{ message }}</div>{% endif %}
    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control"
                   autofocus
                   type="text"
                   name="username"
                   placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control"
                   type="email"
                   name="email"
                   placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control"
                   type="password"
                   name="password"
                   placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control"
                   type="password"
                   name="confirmation"
                   placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>
    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>
{% endblock body %}